version: '3.8'

services:
  goapi:
    restart: unless-stopped
    container_name: goapi
    build:
      context: .
      dockerfile: ./goapi/Dockerfile
    ports:
      - '9090:9090'
    volumes:
      - "./goapi/db:/goapi/db"
  angolar:
    restart: unless-stopped
    container_name: angolar
    build:
      context: .
      dockerfile: ./angolar/Dockerfile
    ports:
      - '80:80'
      - '9091:443'
#  nginx:
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - '443:443'
#      - '80:80'
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile