version: '3.4'

services:
  goapi:
    restart: always
    container_name: goapi
    build:
      context: .
      dockerfile: ./goapi/Dockerfile
    ports:
      - '9090:9090'
  angolar:
    restart: always
    container_name: angolar
    build:
      context: .
      dockerfile: ./angolar/Dockerfile
    ports:
      - '9091:80'
      - '443:443'
    volumes:
      - ~/Documents/certs/nginx.crt:/etc/ssl/certs
      - ~/Documents/certs/nginx.key:/etc/ssl/private
      - ~/Documents/certs/dhparam.pem:/etc/nginx
    depends_on:
      - goapi