version: '3.4'

services:
  goapi:
    restart: always
    container_name: goapi
    build:
      context: .
      dockerfile: ./goapi/Dockerfile
    ports:
      - '9090:80'
      - '443:443'
  angolar:
    restart: always
    container_name: angolar
    build:
      context: .
      dockerfile: ./angolar/Dockerfile
    ports:
      - '9091:9091'
    depends_on:
      - goapi