basePath: /api
definitions:
  models.Redirection:
    properties:
      created_at:
        type: string
      id:
        type: integer
      redirect_url:
        type: string
      shortcut:
        type: string
      updated_at:
        type: string
      views:
        type: integer
    type: object
  models.RedirectionInput:
    properties:
      redirect_url:
        type: string
      shortcut:
        type: string
    required:
    - redirect_url
    - shortcut
    type: object
  models.SignedResponse:
    properties:
      jwt_token:
        type: string
      message:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  models.UserInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: louissantucci1998@gmail.com
    name: SANTUCCI Louis
  description: A redirection app made in Go with Gin Framework.
  title: GoApp
  version: "1.0"
paths:
  /redirection:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Redirection'
            type: array
      summary: Get all redirections
      tags:
      - redirection
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RedirectionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Redirection'
            type: array
        "400":
          description: Bad Request
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Creates a new redirection
      tags:
      - redirection
  /redirection/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
          schema: {}
      summary: Deletes a redirection in function of its ID
      tags:
      - redirection
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Redirection'
        "404":
          description: Not Found
          schema: {}
      summary: Get one redirection in function of its ID
      tags:
      - redirection
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RedirectionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Redirection'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Updates a redirection in function of its ID
      tags:
      - redirection
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Redirection'
            type: array
        "404":
          description: Not Found
          schema: {}
      summary: Increments number of view for one redirection in fucntion of its ID
      tags:
      - redirection
  /user/edit/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - ApiKeyAuth: []
      summary: Edits user in DB
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SignedResponse'
        "403":
          description: Forbidden
      summary: Generates JWT token by verifying user credentials
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Creates new User in DB
      tags:
      - user
swagger: "2.0"
